AppTest/Models/Department.cs
using System.ComponentModel.DataAnnotations;

namespace AppTest.Models
{
    public class Department
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }
        public string? Address { get; set; }

        [Required]
        public string Maneger { get; set; }
    }
}

AppTest/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AppTest.Data;
using AppTest.Models;

namespace AppTest.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DepartmentsController(ApplicationDbContext context)
        {       
            _context = context;
        }

        // GET: Departments
        public async Task<IActionResult> Index()
        {
              return _context.Department != null ? 
                          View(await _context.Department.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Department'  is null.");
            
        }

        // GET: Departments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Department == null)
            {
                return NotFound();
            }

            var department = await _context.Department
                .FirstOrDefaultAsync(m => m.Id == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // GET: Departments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Departments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Address,Maneger")] Department department)
        {
            if (ModelState.IsValid)
            {
                _context.Add(department);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        // GET: Departments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Department == null)
            {
                return NotFound();
            }

            var department = await _context.Department.FindAsync(id);
            if (department == null)
            {
                return NotFound();
            }
            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Address,Maneger")] Department department)
        {
            if (id != department.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(department);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartmentExists(department.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        // GET: Departments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Department == null)
            {
                return NotFound();
            }

            var department = await _context.Department
                .FirstOrDefaultAsync(m => m.Id == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Department == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Department'  is null.");
            }
            var department = await _context.Department.FindAsync(id);
            if (department != null)
            {
                _context.Department.Remove(department);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DepartmentExists(int id)
        {
          return (_context.Department?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

AppTest/Controllers/EmployeesController.cs
using AppTest.Data;
using AppTest.Models;
using AppTest.Models.ModelDTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.AccessControl;

namespace AppTest.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmployeesController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(int? Id)
        {
            if (Id == null)
            {
                var model = await _context.Users.ToListAsync();
                return View(model);
            }
            else
            {
                var model = await _context.Users.Where(e => e.IdDepartment == Id).ToListAsync();
                return View(model);
            }
        }

        public async Task<IActionResult> ChangeAvatar(string? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            else
            {
                var employee = await _context.Users.FindAsync(Id);
                if (employee == null)
                {
                    return NotFound();
                }
                return View(employee);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangeAvatar(string Id, string img)
        {
            var model = await _context.Users.FindAsync(Id);
            if (model == null)
            {
                return NotFound();
            }
            else
            {
                model.Img = img;
                _context.Users.Update(model);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
        }
        public async Task<IActionResult> TimeSheetByMonth(int? Month)
        {
            List<string> listTime = new List<string>();
            if (Month != null)
            {
                Dictionary<string, TimeSpan> ToltalTime = new Dictionary<string, TimeSpan>();

                var model = await _context.TimeSheet.Where(t => t.Start.Month == Month).Include(e => e.employee).AsNoTracking().ToListAsync();
                if (model.Count == 0)
                {
                    return View();
                }
                else
                {
                    for (int i = 0; i < model.Count; i++)
                    {
                        TimeSpan totalTime = new TimeSpan();
                        var item = model[i];
                        if (item.BreakStart == null)
                        {
                            totalTime = (TimeSpan)(item.End - item.Start);
                            listTime.Add((totalTime.TotalMinutes / 60).ToString("##.0##"));
                        }
                        else
                        {
                            totalTime = (TimeSpan)(item.BreakStart - item.Start) + (TimeSpan)(item.End - item.BreakEnd);
                            listTime.Add((totalTime.TotalMinutes / 60).ToString("##.0##"));
                        }

                        if (ToltalTime.TryAdd(item.IdEmployment, totalTime) == false)
                        {
                            var a = ToltalTime.TryGetValue(item.IdEmployment, out var b);
                            b += totalTime;
                            ToltalTime[item.IdEmployment] = b;
                        }
                    }
                    ViewBag.Time = listTime;
                    if (ToltalTime.MaxBy(i => i.Value).Key != null)
                    {
                        var n = ToltalTime.MaxBy(i => i.Value);
                        var m = n.Key;
                        var time = n.Value;
                        ViewBag.Max = (time.TotalMinutes / 60).ToString("##0.##");
                        var employee = await _context.Users.FindAsync(m);
                        ViewBag.Employee = employee.FirstName + " " + employee.LastName;
                    }
                    return View(model);
                }
            }
            else
            {
                var model = await _context.TimeSheet.Include(e => e.employee).AsNoTracking().ToListAsync();
                for (int i = 0; i < model.Count; i++)
                {
                    TimeSpan totalTime = new TimeSpan();
                    var item = model[i];
                    if (item.BreakStart == null)
                    {
                        totalTime = (TimeSpan)(item.End - item.Start);
                        listTime.Add((totalTime.TotalMinutes / 60).ToString("##.0##"));
                    }
                    else
                    {
                        totalTime = (TimeSpan)(item.BreakStart - item.Start) + (TimeSpan)(item.End - item.BreakEnd);
                        listTime.Add((totalTime.TotalMinutes / 60).ToString("##.0##"));
                    }
                }
                ViewBag.Time = listTime;


                if (model == null)
                {
                    return NotFound();
                }
                return View(model);
            }
        }

        public async Task<IActionResult> CalculateSalary(int? Month)
        {
            if (Month == null)
            {
                return View();
            }
            const double regularPayment = 3.125;
            Dictionary<string, TimeSpan> ToltalTime = new Dictionary<string, TimeSpan>();
            Dictionary<Employee, double> Salary = new Dictionary<Employee, double>();
            var model = await _context.TimeSheet.Where(t => t.Start.Month == Month).Include(e => e.employee).AsNoTracking().ToListAsync();
            if (model == null)
            {
                return NotFound();
            }

            for (int i = 0; i < model.Count; i++)
            {
                TimeSpan totalTime = new TimeSpan();
                var item = model[i];
                if (item.BreakStart == null)
                {
                    totalTime = (TimeSpan)(item.End - item.Start);
                }
                else
                {
                    totalTime = (TimeSpan)(item.BreakStart - item.Start) + (TimeSpan)(item.End - item.BreakEnd);
                }

                if (ToltalTime.TryAdd(item.IdEmployment, totalTime) == false)
                {
                    var a = ToltalTime.TryGetValue(item.IdEmployment, out var b);
                    b += totalTime;
                    ToltalTime[item.IdEmployment] = b;
                }
            }
            foreach (var employee in ToltalTime)
            {
                if (employee.Value.TotalMinutes / 60 < 40)
                {
                    var a = await _context.Users.FindAsync(employee.Key);
                    var b = (employee.Value.TotalMinutes / 60) * regularPayment;
                    Salary.Add(a, b);
                }
                else
                {
                    var a = await _context.Users.FindAsync(employee.Key);
                    var b = (employee.Value.TotalMinutes / 60) * regularPayment * 1.5;
                    Salary.Add(a, b);
                }
            }
            return View(Salary);
        }

        public async Task<IActionResult> Infor(string Id)
        {
            var model = await _context.Users.Include(i => i.department).FirstOrDefaultAsync(i => i.Id == Id);
            if (model == null) return NotFound();
            return View(model);
        }
    }
}

AppTest/Views/Departments/Create.cshtml
@model AppTest.Models.Department

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Department</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Maneger" class="control-label"></label>
                <input asp-for="Maneger" class="form-control" />
                <span asp-validation-for="Maneger" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppTest/Views/Departments/Delete.cshtml
@model AppTest.Models.Department

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Department</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Maneger)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Maneger)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AppTest/Views/Departments/Details.cshtml
@model AppTest.Models.Department

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Department</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Maneger)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Maneger)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AppTest/Views/Departments/Edit.cshtml
@model AppTest.Models.Department

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Department</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Maneger" class="control-label"></label>
                <input asp-for="Maneger" class="form-control" />
                <span asp-validation-for="Maneger" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppTest/Views/Departments/Index.cshtml
@model IEnumerable<AppTest.Models.Department>

@{
    ViewData["Title"] = "Index";
}

<h1><b><i class="bi bi-card-list"></i> Department</b></h1>

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-12 text-end">
                <a asp-controller="Departments" asp-action="Create" class="btn btn-outline-success"><i class="bi bi-plus-square-fill"></i> Add Department</a>
                <a asp-controller="Employees" asp-action="TimeSheetByMonth" class="btn btn-outline-warning"><i class="bi bi-box-arrow-in-up"></i>List TimeSheet Month</a>
                <a class="btn btn-outline-success" asp-area="Identity" asp-page="/Account/Register">Register</a>
            </div>

        </div>
    </div>

    <div class="card-body p-3">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col" class="text-center">Department's Name'</th>
                    <th scope="col" class="text-center">Address</th>
                    <th scope="col" class="text-center">Maneger</th>
                    <th scope="col" class="text-center"></th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th scope="row" class="text-center align-middle">@item.Name</th>
                        <td class="text-center align-middle">@item.Address</td>
                        <td class="text-center align-middle">@item.Maneger</td>
                        <td class="text-center align-middle">
                            <a asp-controller="Employees" asp-action="Index" asp-route-Id="@item.Id" class="btn btn-outline-warning"><i class="bi bi-box-arrow-in-up"></i>List Employee</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>