AppTest/Models/Employee.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;

namespace AppTest.Models 
{
    public class Employee : IdentityUser
    { 
        [Required]
        public string FirstName { get; set; }

        [Required]
        public string LastName { get; set; }

        [Required]
        public int Age { get; set; }

        [Required]
        public string Sex { get; set; }

        [Required]
        public DateTime Birthday { get; set; }
        public string? Address { get; set; }

        [Required]
        [ForeignKey("department")]
        public int IdDepartment { get; set; }
        public Department? department { get; set; }

        public string? Img { get; set; }

        public DateTime? Create_At { get; set; } = DateTime.Now;
    }
}

AppTest/Controllers/EmployeesController.cs
using AppTest.Data;
using AppTest.Models;
using AppTest.Models.ModelDTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.AccessControl;

namespace AppTest.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmployeesController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(int? Id)
        {
            if (Id == null)
            {
                var model = await _context.Users.ToListAsync();
                return View(model);
            }
            else
            {
                var model = await _context.Users.Where(e => e.IdDepartment == Id).ToListAsync();
                return View(model);
            }
        }

        public async Task<IActionResult> ChangeAvatar(string? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            else
            {
                var employee = await _context.Users.FindAsync(Id);
                if (employee == null)
                {
                    return NotFound();
                }
                return View(employee);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangeAvatar(string Id, string img)
        {
            var model = await _context.Users.FindAsync(Id);
            if (model == null)
            {
                return NotFound();
            }
            else
            {
                model.Img = img;
                _context.Users.Update(model);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
        }
        public async Task<IActionResult> TimeSheetByMonth(int? Month)
        {
            List<string> listTime = new List<string>();
            if (Month != null)
            {
                Dictionary<string, TimeSpan> ToltalTime = new Dictionary<string, TimeSpan>();

                var model = await _context.TimeSheet.Where(t => t.Start.Month == Month).Include(e => e.employee).AsNoTracking().ToListAsync();
                if (model.Count == 0)
                {
                    return View();
                }
                else
                {
                    for (int i = 0; i < model.Count; i++)
                    {
                        TimeSpan totalTime = new TimeSpan();
                        var item = model[i];
                        if (item.BreakStart == null)
                        {
                            totalTime = (TimeSpan)(item.End - item.Start);
                            listTime.Add((totalTime.TotalMinutes / 60).ToString("##.0##"));
                        }
                        else
                        {
                            totalTime = (TimeSpan)(item.BreakStart - item.Start) + (TimeSpan)(item.End - item.BreakEnd);
                            listTime.Add((totalTime.TotalMinutes / 60).ToString("##.0##"));
                        }

                        if (ToltalTime.TryAdd(item.IdEmployment, totalTime) == false)
                        {
                            var a = ToltalTime.TryGetValue(item.IdEmployment, out var b);
                            b += totalTime;
                            ToltalTime[item.IdEmployment] = b;
                        }
                    }
                    ViewBag.Time = listTime;
                    if (ToltalTime.MaxBy(i => i.Value).Key != null)
                    {
                        var n = ToltalTime.MaxBy(i => i.Value);
                        var m = n.Key;
                        var time = n.Value;
                        ViewBag.Max = (time.TotalMinutes / 60).ToString("##0.##");
                        var employee = await _context.Users.FindAsync(m);
                        ViewBag.Employee = employee.FirstName + " " + employee.LastName;
                    }
                    return View(model);
                }
            }
            else
            {
                var model = await _context.TimeSheet.Include(e => e.employee).AsNoTracking().ToListAsync();
                for (int i = 0; i < model.Count; i++)
                {
                    TimeSpan totalTime = new TimeSpan();
                    var item = model[i];
                    if (item.BreakStart == null)
                    {
                        totalTime = (TimeSpan)(item.End - item.Start);
                        listTime.Add((totalTime.TotalMinutes / 60).ToString("##.0##"));
                    }
                    else
                    {
                        totalTime = (TimeSpan)(item.BreakStart - item.Start) + (TimeSpan)(item.End - item.BreakEnd);
                        listTime.Add((totalTime.TotalMinutes / 60).ToString("##.0##"));
                    }
                }
                ViewBag.Time = listTime;


                if (model == null)
                {
                    return NotFound();
                }
                return View(model);
            }
        }

        public async Task<IActionResult> CalculateSalary(int? Month)
        {
            if (Month == null)
            {
                return View();
            }
            const double regularPayment = 3.125;
            Dictionary<string, TimeSpan> ToltalTime = new Dictionary<string, TimeSpan>();
            Dictionary<Employee, double> Salary = new Dictionary<Employee, double>();
            var model = await _context.TimeSheet.Where(t => t.Start.Month == Month).Include(e => e.employee).AsNoTracking().ToListAsync();
            if (model == null)
            {
                return NotFound();
            }

            for (int i = 0; i < model.Count; i++)
            {
                TimeSpan totalTime = new TimeSpan();
                var item = model[i];
                if (item.BreakStart == null)
                {
                    totalTime = (TimeSpan)(item.End - item.Start);
                }
                else
                {
                    totalTime = (TimeSpan)(item.BreakStart - item.Start) + (TimeSpan)(item.End - item.BreakEnd);
                }

                if (ToltalTime.TryAdd(item.IdEmployment, totalTime) == false)
                {
                    var a = ToltalTime.TryGetValue(item.IdEmployment, out var b);
                    b += totalTime;
                    ToltalTime[item.IdEmployment] = b;
                }
            }
            foreach (var employee in ToltalTime)
            {
                if (employee.Value.TotalMinutes / 60 < 40)
                {
                    var a = await _context.Users.FindAsync(employee.Key);
                    var b = (employee.Value.TotalMinutes / 60) * regularPayment;
                    Salary.Add(a, b);
                }
                else
                {
                    var a = await _context.Users.FindAsync(employee.Key);
                    var b = (employee.Value.TotalMinutes / 60) * regularPayment * 1.5;
                    Salary.Add(a, b);
                }
            }
            return View(Salary);
        }

        public async Task<IActionResult> Infor(string Id)
        {
            var model = await _context.Users.Include(i => i.department).FirstOrDefaultAsync(i => i.Id == Id);
            if (model == null) return NotFound();
            return View(model);
        }
    }
}

AppTest/Controllers/TimeSheetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AppTest.Data;
using AppTest.Models;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AppTest.Controllers
{
    public class TimeSheetsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TimeSheetsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: TimeSheets
        public async Task<IActionResult> Index(string? Id)
        {
            TimeSpan total = new TimeSpan();
            if(Id == null)
            {
                var applicationDbContext = _context.TimeSheet.Include(t => t.employee);
                return View(await applicationDbContext.ToListAsync());
            }
            else
            {
                var applicationDbContext = await _context.TimeSheet.Where(t => t.IdEmployment == Id).Include(t => t.employee).ToListAsync();
                for (int i = 0; i < applicationDbContext.Count(); i++)
                {
                    var item = applicationDbContext[i];
                    if(item.BreakStart == null)
                    {
                        total += (TimeSpan)(item.End - item.Start);
                    }
                    else
                    {
                        total += (TimeSpan)(item.End - item.Start) - (TimeSpan)(item.BreakEnd - item.BreakStart);
                    }                 
                }
                var timeover = total.TotalMinutes / 60;
                ViewBag.Total = timeover.ToString("##0.##");

                List<double> listHour = new List<double>();
                
                for(int i = 0; i < applicationDbContext.Count(); i++)
                {
                    var item = applicationDbContext[i];
                    if(item.BreakStart == null)
                    {
                        var time = (TimeSpan)(item.End - item.Start);
                        listHour.Add(time.TotalMinutes / 60);
                    }
                    else
                    {
                        var time = (TimeSpan)(item.BreakStart - item.Start) + (TimeSpan)(item.End - item.BreakEnd);
                        listHour.Add(time.TotalMinutes / 60);
                    }
                }
                ViewBag.Hour = listHour;

                return View(applicationDbContext);
            }
          
        }

        // GET: TimeSheets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TimeSheet == null)
            {
                return NotFound();
            }

            var timeSheet = await _context.TimeSheet
                .Include(t => t.employee)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (timeSheet == null)
            {
                return NotFound();
            }

            return View(timeSheet);
        }

        // GET: TimeSheets/Create
        public IActionResult Create()
        {
            ViewData["IdEmployment"] = new SelectList(_context.Users, "Id", "FirstName");
            return View();
        }

        // POST: TimeSheets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IdEmployment,Start,BreakStart,BreakEnd,End")] TimeSheet timeSheet)
        {
            if (ModelState.IsValid)
            {
                _context.Add(timeSheet);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdEmployment"] = new SelectList(_context.Users, "Id", "Id", timeSheet.IdEmployment);            
            return View(timeSheet);
        }

        // GET: TimeSheets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TimeSheet == null)
            {
                return NotFound();
            }

            var timeSheet = await _context.TimeSheet.FindAsync(id);
            if (timeSheet == null)
            {
                return NotFound();
            }
            ViewData["IdEmployment"] = new SelectList(_context.Users, "Id", "FirstName", timeSheet.IdEmployment);
            return View(timeSheet);
        }

        // POST: TimeSheets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, TimeSheet timeSheet)
        {


            if (id != timeSheet.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(timeSheet);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TimeSheetExists(timeSheet.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdEmployment"] = new SelectList(_context.Users, "Id", "Id", timeSheet.IdEmployment);
            return View(timeSheet);
        }

        // GET: TimeSheets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TimeSheet == null)
            {
                return NotFound();
            }

            var timeSheet = await _context.TimeSheet
                .Include(t => t.employee)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (timeSheet == null)
            {
                return NotFound();
            }

            return View(timeSheet);
        }

        // POST: TimeSheets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TimeSheet == null)
            {
                return Problem("Entity set 'ApplicationDbContext.TimeSheet'  is null.");
            }
            var timeSheet = await _context.TimeSheet.FindAsync(id);
            if (timeSheet != null)
            {
                _context.TimeSheet.Remove(timeSheet);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TimeSheetExists(int id)
        {
          return (_context.TimeSheet?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

AppTest/Views/Employees/CalculateSalary.cshtml
@model Dictionary<Employee, double>

<h1><b>Calculate salary's employee</b></h1>
<div class="card-header">
    <form asp-controller="Employees" asp-action="CalculateSalary" method="get">
        <div class="row">
            <div class="col-md-12 text-end">
                <div class="form-group">
                </div>
                <div class="form-group">
                    Month: <input type="text" name="Month" />
                    <input type="submit" value="Search" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </form>

</div>
<div class="card-body p-3">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col" style="width:150px;" class="text-center">Employee's Name</th>
                <th scope="col" style="width:150px;" class="text-center">Total worked</th>
                <th scope="col" style="width:200px;" class="text-center">Salary</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {

                <tr>
                    <th scope="row" class="text-center align-middle">@item.Key.FirstName @item.Key.LastName</th>
                    <td class="text-center align-middle">@((item.Value/3.125).ToString("##0.##")) Hours/Month</td>
                    <td class="text-center align-middle">@item.Value.ToString("c")</td>
                </tr>
            }
        </tbody>
    </table>
</div>

AppTest/Views/Employees/ChangeAvatar.cshtml
@model  AppTest.Models.Employee

<div class="row">
    <div class="col-md-4">
        <form asp-action="ChangeAvatar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <h3>Old Avatar</h3>
            <div class="form-group">
                
                <img src="~/Img/@Model.Img" alt="Avatar" width="100" height="100">
                <span asp-validation-for="Img" class="text-danger"></span>
            </div>
            <br />
            <h3>Choose new Avater</h3>
            <div class="form-group">
                <input asp-for="Img" class="form-control" type="file"/>
                <span asp-validation-for="Img" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

AppTest/Views/Employees/Index.cshtml
@model IEnumerable<AppTest.Models.Employee>

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-12 text-end">
                @*<a asp-controller="Departments" asp-action="Create" class="btn btn-outline-success"><i class="bi bi-plus-square-fill"></i> Add Department</a>*@
            </div>

        </div>
    </div>

    <div class="card-body p-3">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col" class="text-center">Name</th>
                    <th scope="col" class="text-center">Mail</th>
                    <th scope="col" class="text-center">Address</th>
                    <th scope="col" class="text-center">Birthday</th>
                    <th scope="col" class="text-center">Avatar</th>
                    <th scope="col" class="text-center"></th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th scope="row" class="text-center align-middle">@item.FirstName @item.LastName</th>
                        <td class="text-center align-middle">@item.Email</td>
                        <td class="text-center align-middle">@item.Address</td>
                        <td class="text-center align-middle">@item.Birthday</td>
                        <td class="text-center align-middle">
                            <img src="~/Img/@item.Img" alt="Avatar" width="100" height="100">
                        </td>
                        <td class="text-center align-middle">
                            <a asp-controller="TimeSheets" asp-action="Index" asp-route-Id="@item.Id" class="btn btn-outline-warning"><i class="bi bi-box-arrow-in-up"></i>TimeSheet</a>
                            <a asp-controller="Employees" asp-action="ChangeAvatar" asp-route-Id="@item.Id" class="btn btn-outline-info"><i class="bi bi-box-arrow-in-up"></i>Change Avatar</a>
                            <a asp-controller="Employees" asp-action="Infor" asp-route-Id="@item.Id" class="btn btn-outline-success"><i class="bi bi-box-arrow-in-up"></i>Detail information</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

AppTest/Views/Employees/Infor.cshtml
@model AppTest.Models.Employee

<h1>Information Employee</h1>

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6">
                <img src="~/Img/@Model.Img" alt="Avatar" width="100" height="100">
            </div>
        </div>
    </div>

    <div class="card-body p-3">
        <div class="row">
            <div class="col-2 pt-3">
                <label asp-for="FirstName" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pt-3">
                <input asp-for="FirstName" class="form-control" disabled />
            </div>

            <div class="col-2 pt-3">
                <label asp-for="LastName" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pt-3">
                <input asp-for="LastName" class="form-control" disabled />
            </div>

            <div class="col-2 pt-3">
                <label asp-for="Sex" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pt-3">
                <input asp-for="Sex" class="form-control" disabled />
            </div>

            <div class="col-2 pt-3">
                <label asp-for="Email" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pt-3">
                <input asp-for="Email" class="form-control" disabled />
            </div>

            <div class="col-2 pt-3">
                <label asp-for="UserName" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pt-3">
                <input asp-for="UserName" class="form-control" disabled />
            </div>

            <div class="col-2 pt-3">
                <label asp-for="PhoneNumber" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pt-3">
                <input asp-for="PhoneNumber" class="form-control" disabled />
            </div>

            <div class="col-2 pt-3">
                <label asp-for="Birthday" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pt-3">
                <input asp-for="Birthday.Date" class="form-control" disabled />
            </div>

            <div class="col-2 pt-3">
                <label asp-for="department" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pt-3">
                <input asp-for="department.Name" class="form-control" disabled />
            </div>

            <div class="col-2 pt-3">
                <label asp-for="Create_At" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pt-3">
                <input asp-for="Create_At.Value.Date" class="form-control" disabled />
            </div>


            <div class="col-2 offset-10 pt-3">
                <a asp-action="Index" asp-controller="Employees" class="btn-outline-primary btn form-control"><i class="bi bi-arrow-return-left"></i> Back to list employees</a>
            </div>
        </div>
    </div>

</div>

AppTest/Views/Employees/TimeSheetByMonth.cshtml
@model IEnumerable<AppTest.Models.TimeSheet>
@{
    int i = 0;
}
<h3>Person is the best of month: <i>@ViewBag.Employee</i> with @ViewBag.Max hours/Month</h3>
<div class="card">
    <div class="card-header">
        <form asp-controller="Employees" asp-action="TimeSheetByMonth" method="get">
            <div class="row">
                <div class="col-md-12 text-end">
                    <div class="form-group">
                        Month: <input type="text" name="Month" />
                        <input type="submit" value="Search" class="btn btn-primary" />
                    </div>
                    <div class="form-group">
                        <a asp-controller="Employees" asp-action="CalculateSalary" asp-route-Month="0" class="btn btn-outline-info m-2  "><i class="bi bi-box-arrow-in-up"></i>Salary</a>
                    </div>
                </div>
            </div>


        </form>
    </div>
    @if (Model != null)
    {
        TimeSpan max = new TimeSpan();
        Dictionary<TimeSheet, TimeSpan> hightest = new Dictionary<TimeSheet, TimeSpan>();
        foreach (var item in Model)
        {
            TimeSpan time = new TimeSpan();
            if (item.BreakStart == null)
            {
                time = (TimeSpan)(item.End - item.Start);
                max = time;
            }
            else
            {
                time = (TimeSpan)(item.BreakStart - item.Start) + (TimeSpan)(item.End - item.BreakEnd);
                max = time;
            }
            if (hightest == null)
            {
                hightest.Add(item, max);
            }
            else
            {
                if (hightest.FirstOrDefault().Value < max)
                {
                    hightest.Clear();
                    hightest.Add(item, max);
                }
            }

        }
        <div class="card-body p-3">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th scope="col" style="width:150px;" class="text-center">Employee's Name</th>
                        <th scope="col" style="width:150px;" class="text-center">Day of Month</th>
                        <th scope="col" style="width:200px;" class="text-center">Time start</th>
                        <th scope="col" style="width:150px;" class="text-center">Time BreakStart</th>
                        <th scope="col" style="width:200px;" class="text-center">Time BreakEnd</th>
                        <th scope="col" style="width:300px;" class="text-center">Time end</th>
                        <th scope="col" style="width:300px;" class="text-center">total</th>
                        <th scope="col" class="text-center"></th>
                    </tr>

                    <tr>
                        @{
                            var a = hightest.FirstOrDefault().Key;
                            var b = hightest.FirstOrDefault().Value;
                            double hour = b.TotalMinutes / 60;
                        }
                        <th scope="col" style="width:150px;" class="text-center">@a.employee.FirstName @a.employee.LastName</th>
                        <th scope="col" style="width:150px;" class="text-center"></th>
                        <th scope="col" style="width:200px;" class="text-center"></th>
                        <th scope="col" style="width:150px;" class="text-center"></th>
                        <th scope="col" style="width:200px;" class="text-center"></th>
                        <th scope="col" style="width:300px;" class="text-center"></th>
                        <th scope="col" style="width:300px;" class="text-center">@hour.ToString("##0.##")</th>
                        <th scope="col" class="text-center"></th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <th scope="row" class="text-center align-middle">@item.employee.FirstName @item.employee.LastName</th>
                            <td class="text-center align-middle">@item.Start.Day / @item.Start.Month</td>
                            <td class="text-center align-middle">@item.Start.TimeOfDay</td>
                            @if (item.BreakStart != null)
                            {
                                <td class="text-center align-middle">@item.BreakStart.Value.TimeOfDay</td>
                                <td class="text-center align-middle">@item.BreakEnd.Value.TimeOfDay</td>
                            }
                            else
                            {
                                <td class="text-center align-middle"></td>
                                <td class="text-center align-middle"></td>
                            }
                            <td class="text-center align-middle">@item.End.TimeOfDay</td>
                            <td class="text-center align-middle">
                                @ViewBag.Time[i] Hours
                            </td>
                            <td class="text-center align-middle">
                                <a asp-controller="TimeSheets" asp-action="Edit" asp-route-Id="@item.Id" class="btn btn-outline-warning"><i class="bi bi-box-arrow-in-up"></i>Edit TimeSheets</a>
                                <a asp-controller="TimeSheets" asp-action="Delete" asp-route-Id="@item.Id" class="btn btn-outline-danger"><i class="bi bi-box-arrow-in-up"></i>Delete TimeSheets</a>
                            </td>
                        </tr>
                        i++;
                    }

                </tbody>
            </table>
        </div>
    }
</div>